### ISSUE TITLE
Modularization or forking

### ISSUE THREAD

**Issue by sockeqwe** [squanchy-dev/squanchy-android#575]
Hey there,
so I took a look at the current code base and I have some questions:

1. What would be the recommended way to use the exising code base for droidcon berlin? Would I create a new app module "droidcon berlin" and will it become part of squanchy repository? Should I fork it and maintain my own fork of squanchy (and trying the best to keep it with your original squanchy source code in sync)?
2. What if I don't want to use existing "domain" layer? Some parts like
 - `FavoritesService`
 - `EventService`
 - `ScheduleService`
 - `SearchService`
 - `SpeakerDetailsService`
 - `VenueInfoService`

 are already well defined and have an interface (or it's easy to extract an interface).
Similar to question 1. let's say I would like to write my own `ScheduleService` that uses SQLite, where would I put this `SQLiteScheduleService`? In a module in Squanchy repository? Should I keep this in my own fork? Related to #536 I think.

**Comment by cortinico** [comment]
Hey @sockeqwe, AFAIK we were using branches for each conference instance. 

E.g. this year's droidcon-italy app was the build of the [conf/droidcon-italy-2018](https://github.com/squanchy-dev/squanchy-android/tree/conf/droidcon-turin-2018) branch (same for droidconItaly2017, london2017, etc.)

**Comment by quiro91** [comment]
Hey @sockeqwe! So:

1. We use branches for adding resources specific to the conference (like the app icon, or other strings) so that we build the apk from there and we keep the develop branch untouched by those changes. I like the idea of a module but maybe it's the best one for the future as it would require quite some work as all the code is in the app module right now. 

2. This one is slightly more tricky. I was talking about this with @rock3r before and the idea we envision for the future would be to extract an interface out of the FirestoreDbService and rename the Firestore model so that you could use it with any data source. What are your thoughts about this?

**Comment by rock3r** [comment]
We'd love to make everyone's efforts useful to everybody, so if we can find a common ground that works for everyone and makes you not need to maintain a fork, that would be great. As Lorenzo mentioned we are creating "release branches" for each conference — it's less pain than doing separate modules, and the idea we have for the medium and long run is to have a modularised architecture in which you can control very easily via a config file (likely via code, but as simple as possible) which features are enabled.

The first step for us, which we are trying to start next week, is to restructure/rename services to repositories (e.g., `ScheduleRepository`) and data sources (e.g., `FirebaseDataSource`). At that time we'd extract interfaces for the ones that don't have interfaces yet, and split out two modules, one for the "persistence API" where the repositories sit (with their implementations and the data source interfaces) and one for the data source implementation we have, using Firestore. We'll also eventually split out "feature" modules, one per activity, so that the UI is composed by several of those models, with an "app entry point" module tying everything together.

Domain models will sit in the repository module. Persistence models will be renamed to `Api*` or `Persistence*` or `Db*` (still being discussed) and will sit in the repositories module too. The repositories' responsibility will be to map persistence models to domain models. The data sources will be in charge of obtaining such persistence models from wherever is appropriate — the idea being you can just change the dependency to a certain data source module from the repositories module and be done with it. That's where you could then create your own data source module that uses SQLite/whatever else, and just swap it.

**Comment by sockeqwe** [comment]
Sounds good to me, thanks for your feedback. Regarding modularisation: 
Since time flies by and Droidcon Berlin is in about a month, I would love to help you there. What would be the best way to break things down and to make a plan?
Should we continue this conversation in #536
