### ISSUE TITLE
Rate sessions

### ISSUE THREAD

**Issue by rock3r** [squanchy-dev/squanchy-android#97]
This requires accounts support (see #56), and collects ratings on the database.

**Comment by ScribblyPixels** [comment]
Ready for design review
I will continue this and build a flow if this is an acceptable direction. I'd like to see some animation on the hearts and perhaps other elements.

https://invis.io/DKE1ZA83V#/259620908_Rate_Session

**Comment by rock3r** [comment]
Looks cool, I think we can tweak something though. For example, I would not have the confirmation button to send the vote. I'd just register it as soon as one rating is tapped (I can see a rating going up like a 1 UP text when you tap something to show the app has registered the vote). Maybe the button could be used for sending some textual feedback instead?

I also have a question. How does this integrate in the app? Is this in the talk details screen? Does it start as a "minified" thing that can be tapped and expands to this? Do we have some CTA in the schedule too for this?

**Comment by ScribblyPixels** [comment]
@rock3r Since this was a draft, not all those questions have been considered.  I like the idea of instant response. I'll work that up. And in terms of the logical flow of this whole thing in app, I'm not sure. Two ways in my mind... I wonder if it should be time and location based?  I don't know what we can technically achieve.  It could be too much of a reliance on automation.  Can scribble up some flows and see how it goes :)

**Comment by rock3r** [comment]
Absolutely. Up for rubberducking and for resizing your wild dream with the cold sword of feasibility :D
